### ISSUE TITLE
Cannot predict some files

### ISSUE THREAD

**Issue by akashicMarga** [HPI-DeepLearning/crnn-lid#14]
while predicting some audio file I am getting the following error

```pyhton
Using TensorFlow backend.

Traceback (most recent call last):

  File "predict.py", line 41, in <module>

    predict(cli_args)

  File "predict.py", line 16, in predict

    data = np.stack(data)

  File "/home/gamut/anaconda2/envs/xyz/li/lib/python2.7/site-packages/numpy/core/shape_base.py", line 335, in stack

    raise ValueError('need at least one array to stack')

ValueError: need at least one array to stack
```

**Comment by ibro45** [comment]
Hi Aki58, I think the problem is in the dimensionality of the data, it sometimes happens that the generated spectogram images are a bit shorter than supposed. Check [this issue that I had](https://github.com/HPI-DeepLearning/crnn-lid/issues/11) and see if you can get something with the Spectrogram generator's small x parameter (the total width of the spectrogram image). Basically what I think is happening to you is that you're trying to predict on an audio file which is converted to a spectrogram but not to the expected dimension and therefore the prediction fails.
I unfortunately hadn't had time to make a pull request to this repo, but this change has been applied in the [version that I forked](https://github.com/ibro45/Language-Identification-Speech/blob/d59915e911d92e5787cd0bfc1aef334749507ccf/tensorflow/SpectrogramGenerator.py#L58)

**Comment by akashicMarga** [comment]
Hi ibro45,
Thanks for your help, I also thought that this might be the case as I was providing 2-3 seconds of the audio file to predict. I will make the appropriate changes as suggested by you.

**Comment by completelyboofyblitzed** [comment]
Hi @ibro45 ,
Your decision didn't work for me, still getting the same error on some files, some work out fine with both yours and the original code.
